### ISSUE TITLE
Allow NexEngine on aternos.org?

### ISSUE THREAD

**Issue by pavog** [nulli0n/NexEngine-spigot#15]
Hi, I am Paul from aternos.org.
aternos.org is the world's largest platform for users to create their own free Minecraft server.

We have a list of plugins and mods that our users can install on their servers.
We offer a suggestion feature where users can suggest plugins and mods.
Normally we only support mods and plugins from websites for mods and plugins like spigotmc.org, modrinth.com or curseforge.com.

We show the available versions of the mods / plugins in our list for the user to download. We download the mods / plugins from the "official" sources to the user's server. We do not redistribute or host the mods / plugins.

Many of our users would like to use your plugins (ExcellentEnchants + ExcellentCrates) on their Aternos servers. Since NexEngine is no longer bundled with this plugin, our users can no longer use these plugins.
Therefore, many of our users ask us if we can add NexEngine to our plugin list.

As I said before: Normally we only support plugins / mods from "official" project sites, but we would make an exception here and add NexEngine with it's versions from the releases on this GitHub project site.
So I would like to ask for your permission if we can add this project to the list of plugins on Aternos and allow our users to download it to our their servers from these GitHub project releases.

**Comment by UsefullSpoon** [comment]
yes

**Comment by nulli0n** [comment]
No.

**Comment by Zosiaax** [comment]
Yes please
