### ISSUE TITLE
Attempted Installation on 1.19.3

### ISSUE THREAD

**Issue by UltimateInfamous** [nulli0n/NexEngine-spigot#24]
I've installed https://www.spigotmc.org/resources/excellentshop-3-in-1-multi-currency-shop.50696/ on 1.19.3 and after restarting my server multiple times the plugin does not show on the list of plugins nor does it allow me to any commands.

It claims that it is compatible with 1.19.3 "Spigot 1.17.2 / 1.18.2 / 1.19.2+" direct quote from the plugin

**Comment by UltimateInfamous** [comment]
I tried to get discord support but your discord link is invalid

**Comment by Vrodo** [comment]
Did you update your paper version to the latest

You also need nexengine installed

**Comment by nulli0n** [comment]
Wrong git repo. Use https://github.com/nulli0n/ExcellentShop-spigot/issues
