### ISSUE TITLE
Stuck at loading libraries for an infinite amount of time

### ISSUE THREAD

**Issue by Vrodo** [nulli0n/NexEngine-spigot#25]
![image](https://user-images.githubusercontent.com/66423440/224147586-582ab251-f744-4766-aec9-f96a58e297cc.png)

I have no idea why it's doing this, i've reinstalled nexengine and both plugins that deal with it.

**Comment by Vrodo** [comment]
Update for nulli0n 

I've updated to the latest paper version and switched back to 2.2.7
There was a big difference between the results from 2.2.7 and 2.2.9, here they are:

2.2.9:
![image](https://user-images.githubusercontent.com/66423440/224419522-f56f1609-b642-4f4d-a27c-e74a0c285ef8.png)

2.2.7:
![image](https://user-images.githubusercontent.com/66423440/224419607-2d65b3d2-d6bd-4ea3-80ae-247d7348c535.png)

**Comment by nulli0n** [comment]
I guess it's a problem of internet access/speed of your server on host/PC.
