### ISSUE TITLE
Please update to 1.19.4

### ISSUE THREAD

**Issue by CCjun6** [nulli0n/NexEngine-spigot#28]
I paid for these three plugins
ExcellentShop
ExcellentCreate
Model Engine

Please update this pre-plugin so that I can use these three plugins

**Comment by ZappySK** [comment]
Also having problem.. still waiting for updating these plugins..

**Comment by rentexgfx** [comment]
+1

**Comment by nulli0n** [comment]
At least one from the list is a free one, but ok: https://github.com/nulli0n/NexEngine-spigot/releases/tag/v2.2.10
