### ISSUE TITLE
Unable to load user data error.

### ISSUE THREAD

**Issue by XShoutGamer** [nulli0n/NexEngine-spigot#30]
So, when I add this plugin to my paper 1.19.4 server everything loads up fine and there seems to be no issues. But as soon as I or any other player tries joining, it doesnt let them join with the message "Unable to load your user data".  What could be causing this issue? If its not on my end, please fix it. 

Im using the newest version of this plugin.
![image](https://user-images.githubusercontent.com/90159410/230699119-62ddebb6-8e09-4ee0-9ed0-386473e3daef.png)

**Comment by nulli0n** [comment]
Reset data.db of the plugin

**Comment by mxlt02** [comment]
What does data.db mean

**Comment by Sakuraiina** [comment]
> data.db 是什么意思

直接删除nexengine插件配置文件
