### ISSUE TITLE
Error reported by player after entering the server

### ISSUE THREAD

**Issue by HiTech0926** [nulli0n/NexEngine-spigot#39]
As shown in the figure, the server uses NexEngine front-end. But recently, players have reported errors every time they enter the server. The NexEngine version is 2.2.8 build-19/01/2023, and the server version is Purpur 1.19.2.
![image](https://github.com/nulli0n/NexEngine-spigot/assets/112369933/d5dda7d8-709b-4f46-95de-945c21aa84d9)

Sorry, I don't speak English. I use Baidu Translate.

**Comment by nulli0n** [comment]
Update NexEngine and reset data.db inside Crates folder.
