### ISSUE TITLE
PROBLEM WHIT ITEMS ADDER FURNITURE 

### ISSUE THREAD

**Issue by bladeRR** [nulli0n/NexEngine-spigot#55]
there is a problem with the furniture when you install nextengine, you can not break the blocks, the bad thing is that it does not get any kind of error in the console, it just does not let you break the blocks.

**Comment by nulli0n** [comment]
check the source code and you will find out that it does not have any event listeners to be able to cancel your entity/block interactions. this. is. not. even. possible. to be caused by nexengine.

**Comment by bladeRR** [comment]
I'm the one who has the plugin installed, the one who is testing it, I only have nextengine and itemsadder installed and it doesn't let me use furnitre.

**Comment by bladeRR** [comment]
fucking author who doesn't know how to recognize his mistakes, I hope you go to hell, asshole.

**Comment by nulli0n** [comment]
I can only assume that your issue is caused by AdvancedMobArena damage bug which is fixed in reuploaded plugin version (you need to redownload it). 

But your behavior is unacceptable and you're not welcome here and in my discord anymore. You will be banned on both places. Have a nice day!
